CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;
ALTER TABLE depot ALTER COLUMN id TYPE BIGINT USING id::bigint;
ALTER TABLE depot ALTER COLUMN etat TYPE VARCHAR(11);
ALTER TABLE depot ALTER COLUMN type TYPE VARCHAR(8);
ALTER TABLE depot ADD COLUMN id_depot VARCHAR(255) NOT NULL;
ALTER TABLE depot ADD CONSTRAINT UK_hm6srhe12ep3m2shbbnhhic1g unique (id_depot);